[package]
name = "espdap"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-println = { version = "0.9", features = ["defmt-espflash", "esp32s2", "critical-section"], optional = true }
esp-hal = { git = "https://github.com/bugadani/esp-hal.git", branch = "usb", features = [
    "async",
    "embassy",
    "embassy-executor-thread",
    "embassy-executor-interrupt",
    "embedded-hal-02"
] }
esp-backtrace = { version = "0.11.1", features = ["exception-handler", "panic-handler", "defmt"] }

defmt = "0.3"
defmt-rtt = { version = "0.4", optional = true }

static_cell = { version = "2.0.0", features = ["nightly"] }
dap-rs = { git = "https://github.com/korken89/dap-rs.git", features = [ "defmt" ] }
embassy-executor = { version = "0.5.0", features = ["task-arena-size-40960", "defmt"] }
embassy-usb = { git = "https://github.com/embassy-rs/embassy.git", version = "0.2.0", default-features = false, features = ["defmt"] }
replace_with = { version = "0.1.7", default-features = false }

[features]
default = ["esp32s2"]
esp32s2 = ["esp-hal/esp32s2", "esp-backtrace/esp32s2", "esp-hal/embassy-time-systick-80mhz", "esp-println"]
esp32s3 = ["esp-hal/esp32s3", "esp-backtrace/esp32s3", "esp-hal/embassy-time-systick-16mhz", "defmt-rtt"]
